import { FullProviderProfile, Tier, ClinicianType, Language, Condition, PatientDemographic, TrainingLevel } from "@/types";

export const states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"];
export const clinicianTypes: ClinicianType[] = ["Chiropractor", "Physical Therapist", "Athletic Trainer", "Massage Therapist", "Occupational Therapist", "Other", "Medical Doctor"];
export const languages: Language[] = ["English", "Spanish", "French", "German", "Mandarin"];
export const conditions: Condition[] = ["Back Pain", "Neck Pain", "Headaches", "Sports Injuries", "Post-Surgical Rehab", "Plantar Fasciitis", "Tennis Elbow", "Carpal Tunnel Syndrome"];
export const patientDemographics: PatientDemographic[] = ["Athletes", "Pediatrics", "Geriatrics", "General Population"];
export const trainingLevels: TrainingLevel[] = ["M1 Basic", "M2 Advanced", "Certified Specialist", "GTS", "Essential", "Advanced"];
export const specialties = ["Chiropractor", "Physical Therapist", "Athletic Trainer", "Massage Therapist", "Occupational Therapist", "Medical Doctor"];


export const mockProviders: FullProviderProfile[] = [
    {
        id: "1",
        name: "Dr. John Doe",
        specialty: "Chiropractor",
        profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
        location: "New York, NY",
        clinicAddress: "123 Main St, New York, NY 10001",
        coordinates: { lat: 40.7128, lng: -74.0060 },
        tier: "Premier",
        clinicianType: "Chiropractor",
        bio: "Dr. John Doe is a certified Graston Technique provider with over 10 years of experience in treating sports-related injuries. He is passionate about helping athletes return to their peak performance.",
        experience: "10 years",
        education: "D.C. from Palmer College of Chiropractic",
        email: "john.doe@example.com",
        phone: "555-123-4567",
        website: "https://www.johndoechiro.com",
        languages_spoken: ["English"],
        services: ["Spinal Adjustments", "Graston Technique", "Rehabilitation"],
        gt_certifications: ["GTS", "Advanced"],
        verification_badges: ["Verified"],
        accreditation_logos: [{ name: "ACA", logoUrl: "https://via.placeholder.com/50x50?text=ACA", url: "#" }],
        patient_types: ["Athletes", "General Population"],
        conditions_treated: ["Back Pain", "Sports Injuries"],
        rating: 4.9,
        reviewCount: 120,
        isFavorite: false,
        views: 500,
        engagementScore: 85,
        can_compare: true,
        gallery_images: ["https://via.placeholder.com/400x300?text=Clinic+1", "https://via.placeholder.com/400x300?text=Clinic+2"],
        gallery_videos: ["https://www.youtube.com/embed/dQw4w9WgXcQ"],
        testimonials: [{ quote: "Dr. Doe is amazing!", author: "Patient A", rating: 5 }],
        faqs: [{ question: "What is Graston Technique?", answer: "It's an instrument-assisted soft tissue mobilization technique." }],
        linkedin: "https://linkedin.com/in/johndoe",
        facebook: "https://facebook.com/johndoechiro",
    },
    {
        id: "2",
        name: "Dr. Jane Smith",
        specialty: "Physical Therapist",
        profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
        location: "Los Angeles, CA",
        clinicAddress: "456 Oak Ave, Los Angeles, CA 90001",
        coordinates: { lat: 34.0522, lng: -118.2437 },
        tier: "Preferred",
        clinicianType: "Physical Therapist",
        bio: "Dr. Jane Smith specializes in post-surgical rehabilitation and chronic pain management. She integrates the Graston Technique to accelerate recovery and improve patient outcomes.",
        experience: "8 years",
        education: "D.P.T. from University of Southern California",
        email: "jane.smith@example.com",
        phone: "555-987-6543",
        website: "https://www.janesmithpt.com",
        languages_spoken: ["English", "Spanish"],
        services: ["Manual Therapy", "Graston Technique", "Therapeutic Exercise"],
        gt_certifications: ["Essential"],
        patient_types: ["General Population", "Geriatrics"],
        conditions_treated: ["Post-Surgical Rehab", "Neck Pain"],
        rating: 4.8,
        reviewCount: 95,
        isFavorite: true,
        views: 350,
        engagementScore: 78,
        can_compare: true,
        gallery_images: ["https://via.placeholder.com/400x300?text=Clinic+3"],
        testimonials: [{ quote: "Highly recommend Dr. Smith!", author: "Patient B", rating: 4.5 }],
        instagram: "https://instagram.com/janesmithpt",
    },
    {
        id: "3",
        name: "Dr. Robert Turner",
        specialty: "Physical Therapist",
        profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
        location: "Chicago, IL",
        clinicAddress: "789 Pine St, Chicago, IL 60601",
        coordinates: { lat: 41.8781, lng: -87.6298 },
        tier: "Free",
        clinicianType: "Physical Therapist",
        bio: "Dr. Turner has 12 years of experience in orthopedic rehabilitation, using the Graston Technique to treat musculoskeletal injuries and improve mobility.",
        experience: "12 years",
        education: "D.P.T. from Northwestern University",
        email: "robert.turner@example.com",
        phone: "555-111-2222",
        website: "https://www.robertturnerpt.com",
        languages_spoken: ["English"],
        services: ["Graston Technique", "Therapeutic Exercises"],
        gt_certifications: ["GTS"],
        patient_types: ["Athletes"],
        conditions_treated: ["Sports Injuries", "Back Pain"],
        rating: 4.5,
        reviewCount: 70,
        isFavorite: false,
        views: 200,
        engagementScore: 60,
        can_compare: false,
    },
    {
        id: "4",
        name: "Dr. Emily Lee",
        specialty: "Chiropractor",
        profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
        location: "Houston, TX",
        clinicAddress: "101 Elm St, Houston, TX 77001",
        coordinates: { lat: 29.7604, lng: -95.3698 },
        tier: "Premier",
        clinicianType: "Chiropractor",
        bio: "A former collegiate athlete, Dr. Lee specializes in sports rehabilitation, helping athletes recover quickly with advanced manual techniques.",
        experience: "7 years",
        education: "D.C. from Life University",
        email: "emily.lee@example.com",
        phone: "555-333-4444",
        website: "https://www.emilyleechiro.com",
        languages_spoken: ["English", "Mandarin"],
        services: ["Spinal Adjustments", "Graston Technique"],
        gt_certifications: ["Advanced"],
        patient_types: ["Athletes"],
        conditions_treated: ["Sports Injuries"],
        rating: 4.9,
        reviewCount: 150,
        isFavorite: false,
        views: 600,
        engagementScore: 90,
        can_compare: true,
        gallery_images: ["https://via.placeholder.com/400x300?text=Clinic+4"],
        testimonials: [{ quote: "Best chiropractor in Houston!", author: "Patient C", rating: 5 }],
        twitter: "https://twitter.com/emilyleechiro",
    },
    {
        id: "5",
        name: "Dr. Michael Nguyen",
        specialty: "Massage Therapist",
        profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
        location: "Phoenix, AZ",
        clinicAddress: "202 Birch Ln, Phoenix, AZ 85001",
        coordinates: { lat: 33.4484, lng: -112.0740 },
        tier: "Preferred",
        clinicianType: "Massage Therapist",
        bio: "Dr. Nguyen employs neuromuscular techniques alongside Graston to treat chronic pain and soft tissue dysfunction.",
        experience: "9 years",
        education: "D.C. from Palmer College",
        email: "michael.nguyen@example.com",
        phone: "555-555-6666",
        website: "https://www.michaelnguyenmt.com",
        languages_spoken: ["English", "Vietnamese"],
        services: ["Graston Technique", "Deep Tissue Massage"],
        gt_certifications: ["Essential"],
        patient_types: ["General Population"],
        conditions_treated: ["Neck Pain", "Back Pain"],
        rating: 4.7,
        reviewCount: 80,
        isFavorite: false,
        views: 300,
        engagementScore: 70,
        can_compare: true,
    },
    {
        id: "6",
        name: "Dr. Sarah Martinez",
        specialty: "Physical Therapist",
        profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
        location: "Philadelphia, PA",
        clinicAddress: "303 Cedar Rd, Philadelphia, PA 19101",
        coordinates: { lat: 39.9526, lng: -75.1652 },
        tier: "Premier",
        clinicianType: "Physical Therapist",
        bio: "Specializing in manual therapy and the Graston Technique, Dr. Martinez focuses on post-surgical and chronic pain management.",
        experience: "11 years",
        education: "D.P.T. from University of Miami",
        email: "sarah.martinez@example.com",
        phone: "555-777-8888",
        website: "https://www.sarahmartinezpt.com",
        languages_spoken: ["English", "Spanish"],
        services: ["Manual Therapy", "Graston Technique"],
        gt_certifications: ["Advanced", "Essential"],
        patient_types: ["Geriatrics", "General Population"],
        conditions_treated: ["Post-Surgical Rehab", "Headaches"],
        rating: 4.9,
        reviewCount: 110,
        isFavorite: false,
        views: 550,
        engagementScore: 88,
        can_compare: true,
        gallery_images: ["https://via.placeholder.com/400x300?text=Clinic+5"],
        testimonials: [{ quote: "Dr. Martinez helped me recover completely!", author: "Patient D", rating: 5 }],
    },
    {
        id: "7",
        name: "Emily White",
        specialty: "Athletic Trainer",
        profileImage: "https://randomuser.me/api/portraits/women/7.jpg",
        location: "San Antonio, TX",
        clinicAddress: "404 Dogwood Dr, San Antonio, TX 78201",
        coordinates: { lat: 29.4241, lng: -98.4936 },
        tier: "Free",
        clinicianType: "Athletic Trainer",
        bio: "Emily integrates sports massage and Graston Technique to help weekend warriors and professionals alike stay injury-free.",
        experience: "6 years",
        education: "B.S. Kinesiology, UCLA",
        email: "emily.white@example.com",
        phone: "555-222-3333",
        website: "https://www.emilywhiteat.com",
        languages_spoken: ["English"],
        services: ["Sports Massage", "Graston Technique"],
        gt_certifications: ["Essential"],
        patient_types: ["Athletes"],
        conditions_treated: ["Sports Injuries"],
        rating: 4.6,
        reviewCount: 60,
        isFavorite: false,
        views: 180,
        engagementScore: 55,
        can_compare: false,
    },
    {
        id: "8",
        name: "Dr. David O'Connor",
        specialty: "Chiropractor",
        profileImage: "https://randomuser.me/api/portraits/men/8.jpg",
        location: "San Diego, CA",
        clinicAddress: "505 Elmwood Ave, San Diego, CA 92101",
        coordinates: { lat: 32.7157, lng: -117.1611 },
        tier: "Preferred",
        clinicianType: "Chiropractor",
        bio: "With a decade of experience, Dr. O'Connor brings advanced Graston treatments to holistic chiropractic care.",
        experience: "10 years",
        education: "D.C. from Logan University",
        email: "david.oconnor@example.com",
        phone: "555-444-5555",
        website: "https://www.davidoconnorchiro.com",
        languages_spoken: ["English", "Irish"],
        services: ["Spinal Adjustments", "Graston Technique"],
        gt_certifications: ["GTS"],
        patient_types: ["General Population"],
        conditions_treated: ["Back Pain", "Headaches"],
        rating: 4.7,
        reviewCount: 100,
        isFavorite: false,
        views: 400,
        engagementScore: 80,
        can_compare: true,
    },
    {
        id: "9",
        name: "Dr. Priya Patel",
        specialty: "Physical Therapist",
        profileImage: "https://randomuser.me/api/portraits/women/9.jpg",
        location: "Dallas, TX",
        clinicAddress: "606 Maple St, Dallas, TX 75201",
        coordinates: { lat: 32.7767, lng: -96.7970 },
        tier: "Premier",
        clinicianType: "Physical Therapist",
        bio: "Dr. Patel employs myofascial release and Graston techniques to treat connective tissue restrictions and improve function.",
        experience: "5 years",
        education: "M.S. Physical Therapy, Emory University",
        email: "priya.patel@example.com",
        phone: "555-666-7777",
        website: "https://www.priyapatelpt.com",
        languages_spoken: ["English", "Hindi"],
        services: ["Myofascial Release", "Graston Technique"],
        gt_certifications: ["Advanced"],
        patient_types: ["General Population"],
        conditions_treated: ["Neck Pain", "Plantar Fasciitis"],
        rating: 4.8,
        reviewCount: 130,
        isFavorite: false,
        views: 520,
        engagementScore: 87,
        can_compare: true,
        gallery_images: ["https://via.placeholder.com/400x300?text=Clinic+6"],
        testimonials: [{ quote: "Fantastic results with Dr. Patel!", author: "Patient E", rating: 5 }],
    },
    {
        id: "10",
        name: "Dr. Alex Kim",
        specialty: "Medical Doctor",
        profileImage: "https://randomuser.me/api/portraits/men/10.jpg",
        location: "San Jose, CA",
        clinicAddress: "707 Poplar Ave, San Jose, CA 95101",
        coordinates: { lat: 37.3382, lng: -121.8863 },
        tier: "Premier",
        clinicianType: "Medical Doctor",
        bio: "Combining acupuncture, Graston, and manual therapy, Dr. Kim delivers a comprehensive healing approach.",
        experience: "8 years",
        education: "D.C. from National University of Health Sciences",
        email: "alex.kim@example.com",
        phone: "555-888-9999",
        website: "https://www.alexkimm.com",
        languages_spoken: ["English", "Korean"],
        services: ["Acupuncture", "Graston Technique", "Manual Therapy"],
        gt_certifications: ["GTS", "Essential"],
        patient_types: ["General Population"],
        conditions_treated: ["Back Pain", "Headaches"],
        rating: 4.9,
        reviewCount: 140,
        isFavorite: false,
        views: 580,
        engagementScore: 92,
        can_compare: true,
    },
    {
        id: "11",
        name: "Dr. Sofia Rossi",
        specialty: "Massage Therapist",
        profileImage: "https://randomuser.me/api/portraits/women/11.jpg",
        location: "Austin, TX",
        clinicAddress: "808 Willow Way, Austin, TX 78701",
        coordinates: { lat: 30.2672, lng: -97.7431 },
        tier: "Preferred",
        clinicianType: "Massage Therapist",
        bio: "Italian-trained Dr. Rossi integrates European manual therapy techniques with Graston for optimal results.",
        experience: "7 years",
        education: "D.P.T. from University of Milan",
        email: "sofia.rossi@example.com",
        phone: "555-101-2020",
        website: "https://www.sofiarossimt.com",
        languages_spoken: ["English", "Italian"],
        services: ["Neuromuscular Therapy", "Graston Technique"],
        gt_certifications: ["Advanced"],
        patient_types: ["Athletes", "General Population"],
        conditions_treated: ["Sports Injuries", "Neck Pain"],
        rating: 4.7,
        reviewCount: 75,
        isFavorite: false,
        views: 320,
        engagementScore: 75,
        can_compare: true,
    },
    {
        id: "12",
        name: "Dr. Ben Wilson",
        specialty: "Chiropractor",
        profileImage: "https://randomuser.me/api/portraits/men/12.jpg",
        location: "Jacksonville, FL",
        clinicAddress: "909 Cherry St, Jacksonville, FL 32201",
        coordinates: { lat: 30.3322, lng: -81.6557 },
        tier: "Free",
        clinicianType: "Chiropractor",
        bio: "Specialist in spinal rehab and Graston Technique, Dr. Wilson offers personalized recovery plans for chronic conditions.",
        experience: "13 years",
        education: "D.C. from Logan University",
        email: "ben.wilson@example.com",
        phone: "555-303-4040",
        website: "https://www.benwilsonchiro.com",
        languages_spoken: ["English"],
        services: ["Spinal Rehabilitation", "Graston Technique"],
        gt_certifications: ["Essential"],
        patient_types: ["General Population"],
        conditions_treated: ["Back Pain", "Chronic Pain"],
        rating: 4.4,
        reviewCount: 50,
        isFavorite: false,
        views: 150,
        engagementScore: 50,
        can_compare: false,
    },
];

export const mockMarketingResources = [
    {
        id: "1",
        title: "Graston Technique® Brochure",
        description: "A comprehensive brochure explaining the benefits of Graston Technique for patients.",
        category: "Patient Education",
        tier: "Free",
        image: "https://via.placeholder.com/150?text=Brochure",
        filePath: "/docs/brochure.pdf",
    },
    {
        id: "2",
        title: "Social Media Kit: Back Pain",
        description: "Ready-to-use social media graphics and captions focusing on back pain treatment with GT.",
        category: "Social Media",
        tier: "Preferred",
        image: "https://via.placeholder.com/150?text=Social+Kit",
        filePath: "/docs/social-media-kit-back-pain.zip",
    },
    {
        id: "3",
        title: "Advanced GT Protocol Guide",
        description: "Detailed guide on advanced Graston Technique protocols for complex cases.",
        category: "Clinical Resources",
        tier: "Premier",
        image: "https://via.placeholder.com/150?text=Protocol+Guide",
        filePath: "/docs/advanced-protocol-guide.pdf",
    },
    {
        id: "4",
        title: "Patient Testimonial Video Template",
        description: "A customizable video template to collect and showcase patient testimonials.",
        category: "Video Marketing",
        tier: "Premier",
        image: "https://via.placeholder.com/150?text=Video+Template",
        filePath: "/docs/testimonial-video-template.zip",
    },
    {
        id: "5",
        title: "GT Logo Pack",
        description: "Official Graston Technique logos for use on your website and marketing materials.",
        category: "Branding",
        tier: "Free",
        image: "https://via.placeholder.com/150?text=Logos",
        filePath: "/docs/gt-logo-pack.zip",
    },
    {
        id: "6",
        title: "Webinar: Integrating GT into Your Practice",
        description: "Recorded webinar on best practices for integrating Graston Technique into daily clinical practice.",
        category: "Education",
        tier: "Preferred",
        image: "https://via.placeholder.com/150?text=Webinar",
        filePath: "/docs/webinar-integration.mp4",
    },
];