import { FullProviderProfile, Condition, Language, ClinicianType } from "@/types";

export const specialties: ClinicianType[] = ["Chiropractor", "Physical Therapist", "Massage Therapist", "Acupuncturist"];
export const conditions: Condition[] = ["Low Back Pain", "Neck Pain", "Sciatica", "Sports Injuries", "Headaches & Migraines", "Plantar Fasciitis", "Tennis Elbow", "Carpal Tunnel Syndrome"];
export const languages: Language[] = ["English", "Spanish", "French", "Mandarin", "German"];

export const mockProviders: FullProviderProfile[] = [
  {
    id: "1",
    name: "Dr. Evelyn Reed",
    email: "e.reed@example.com",
    specialty: "Chiropractic Care",
    clinician_type: "Chiropractor",
    tier: "Premier",
    phone: "555-0101",
    website: "https://evelynreedchiro.com",
    location: "New York, NY",
    clinic_address: "123 Wellness Ave, New York, NY 10001",
    coordinates: { lat: 40.7128, lng: -74.0060 },
    bio: "Dr. Evelyn Reed is a board-certified chiropractor with over 15 years of experience in treating musculoskeletal conditions. She is passionate about helping patients achieve optimal health through natural and effective care.",
    profile_image: "https://i.pravatar.cc/150?img=1",
    rating: 4.9,
    review_count: 182,
    accepting_new_patients: true,
    services: ["Spinal Adjustment", "Sports Injury Rehab", "Nutritional Counseling"],
    conditions_treated: ["Low Back Pain", "Neck Pain", "Sciatica"],
    languages_spoken: ["English", "Spanish"],
    certifications: ["Graston Technique Certified", "Webster Technique"],
  },
  {
    id: "2",
    name: "John Carter, PT",
    email: "j.carter@example.com",
    specialty: "Physical Therapy",
    clinician_type: "Physical Therapist",
    tier: "Preferred",
    phone: "555-0102",
    website: "https://carterphysicaltherapy.com",
    location: "Los Angeles, CA",
    clinic_address: "456 Recovery Rd, Los Angeles, CA 90012",
    coordinates: { lat: 34.0522, lng: -118.2437 },
    bio: "John Carter is a licensed physical therapist specializing in post-operative rehabilitation and sports medicine. He believes in a patient-centered approach to recovery.",
    profile_image: "https://i.pravatar.cc/150?img=2",
    rating: 4.8,
    review_count: 120,
    accepting_new_patients: false,
    services: ["Post-Surgical Rehab", "Manual Therapy", "Gait Training"],
    conditions_treated: ["Sports Injuries", "Plantar Fasciitis"],
    languages_spoken: ["English"],
    certifications: ["Orthopaedic Clinical Specialist (OCS)"],
  },
  {
    id: "3",
    name: "Maria Garcia, LMT",
    email: "m.garcia@example.com",
    specialty: "Therapeutic Massage",
    clinician_type: "Massage Therapist",
    tier: "Free",
    phone: "555-0103",
    website: "https://mariasmassage.com",
    location: "Chicago, IL",
    clinic_address: "789 Serenity Blvd, Chicago, IL 60605",
    coordinates: { lat: 41.8781, lng: -87.6298 },
    bio: "Maria Garcia offers a range of massage therapies, from deep tissue to Swedish massage, to help clients relieve stress and manage pain.",
    profile_image: "https://i.pravatar.cc/150?img=3",
    rating: 4.9,
    review_count: 250,
    accepting_new_patients: true,
    services: ["Deep Tissue Massage", "Swedish Massage", "Hot Stone Therapy"],
    conditions_treated: ["Neck Pain", "Headaches & Migraines"],
    languages_spoken: ["English", "Spanish"],
    certifications: ["Licensed Massage Therapist"],
  },
  {
    id: "4",
    name: "Dr. Chen Wei",
    email: "c.wei@example.com",
    specialty: "Acupuncture",
    clinician_type: "Acupuncturist",
    tier: "Premier",
    phone: "555-0104",
    website: "https://chenweiacu.com",
    location: "San Francisco, CA",
    clinic_address: "101 Balance St, San Francisco, CA 94102",
    coordinates: { lat: 37.7749, lng: -122.4194 },
    bio: "With a background in Traditional Chinese Medicine, Dr. Chen Wei provides acupuncture and herbal medicine services to promote natural healing.",
    profile_image: "https://i.pravatar.cc/150?img=4",
    rating: 5.0,
    review_count: 95,
    accepting_new_patients: true,
    services: ["Acupuncture", "Cupping", "Herbal Medicine"],
    conditions_treated: ["Headaches & Migraines", "Sciatica", "Carpal Tunnel Syndrome"],
    languages_spoken: ["English", "Mandarin"],
    certifications: ["NCCAOM Certified"],
  },
  {
    id: "5",
    name: "Dr. Samuel Jones",
    email: "s.jones@example.com",
    specialty: "Sports Chiropractic",
    clinician_type: "Chiropractor",
    tier: "Preferred",
    phone: "555-0105",
    website: "https://joneschiro.com",
    location: "Miami, FL",
    clinic_address: "210 Athletic Way, Miami, FL 33130",
    coordinates: { lat: 25.7617, lng: -80.1918 },
    bio: "Dr. Jones focuses on athletes of all levels, helping them recover from injuries and improve performance.",
    profile_image: "https://i.pravatar.cc/150?img=5",
    rating: 4.7,
    review_count: 88,
    accepting_new_patients: true,
    services: ["Performance Care", "Injury Assessment", "Spinal Decompression"],
    conditions_treated: ["Sports Injuries", "Low Back Pain"],
    languages_spoken: ["English"],
    certifications: ["Certified Chiropractic Sports Physician (CCSP)"],
  },
  {
    id: "6",
    name: "Aisha Khan, PT, DPT",
    email: "a.khan@example.com",
    specialty: "Pediatric Physical Therapy",
    clinician_type: "Physical Therapist",
    tier: "Free",
    phone: "555-0106",
    website: "https://aishakhanpt.com",
    location: "Houston, TX",
    clinic_address: "321 Kids First Ln, Houston, TX 77002",
    coordinates: { lat: 29.7604, lng: -95.3698 },
    bio: "Aisha Khan is dedicated to helping children with developmental delays and motor challenges reach their full potential.",
    profile_image: "https://i.pravatar.cc/150?img=6",
    rating: 4.9,
    review_count: 75,
    accepting_new_patients: false,
    services: ["Developmental Screenings", "Torticollis Treatment", "Play-Based Therapy"],
    conditions_treated: [],
    languages_spoken: ["English", "Spanish"],
    certifications: ["Board-Certified Clinical Specialist in Pediatric Physical Therapy (PCS)"],
  },
  {
    id: "7",
    name: "Dr. Ben Carter",
    email: "b.carter@example.com",
    specialty: "Family Chiropractic",
    clinician_type: "Chiropractor",
    tier: "Premier",
    phone: "555-0107",
    website: "https://carterfamilychiro.com",
    location: "Denver, CO",
    clinic_address: "432 Mountain View Dr, Denver, CO 80202",
    coordinates: { lat: 39.7392, lng: -104.9903 },
    bio: "A family-focused practice providing gentle and effective chiropractic care for all ages, from infants to seniors.",
    profile_image: "https://i.pravatar.cc/150?img=7",
    rating: 4.8,
    review_count: 210,
    accepting_new_patients: true,
    services: ["Prenatal Care", "Pediatric Adjustments", "Wellness Care"],
    conditions_treated: ["Low Back Pain", "Headaches & Migraines"],
    languages_spoken: ["English"],
    certifications: ["Graston Technique Certified"],
  },
  {
    id: "8",
    name: "Olivia White, L.Ac.",
    email: "o.white@example.com",
    specialty: "Acupuncture & Wellness",
    clinician_type: "Acupuncturist",
    tier: "Preferred",
    phone: "555-0108",
    website: "https://oliviawhiteacu.com",
    location: "Seattle, WA",
    clinic_address: "543 Evergreen Ter, Seattle, WA 98101",
    coordinates: { lat: 47.6062, lng: -122.3321 },
    bio: "Olivia White integrates acupuncture with holistic health coaching to address a wide range of health concerns, from pain to anxiety.",
    profile_image: "https://i.pravatar.cc/150?img=8",
    rating: 5.0,
    review_count: 150,
    accepting_new_patients: true,
    services: ["Cosmetic Acupuncture", "Stress & Anxiety Relief", "Acupuncture"],
    conditions_treated: ["Neck Pain", "Carpal Tunnel Syndrome"],
    languages_spoken: ["English", "French"],
    certifications: ["NCCAOM Certified"],
  },
  {
    id: "9",
    name: "David Lee, RMT",
    email: "d.lee@example.com",
    specialty: "Sports Massage",
    clinician_type: "Massage Therapist",
    tier: "Free",
    phone: "555-0109",
    website: "https://davidleermt.com",
    location: "Boston, MA",
    clinic_address: "654 Champion Cir, Boston, MA 02108",
    coordinates: { lat: 42.3601, lng: -71.0589 },
    bio: "David Lee is a registered massage therapist who works with athletes to prevent injuries, improve flexibility, and speed up recovery.",
    profile_image: "https://i.pravatar.cc/150?img=9",
    rating: 4.7,
    review_count: 99,
    accepting_new_patients: true,
    services: ["Pre-Event Massage", "Post-Event Massage", "Myofascial Release"],
    conditions_treated: ["Sports Injuries", "Plantar Fasciitis"],
    languages_spoken: ["English"],
    certifications: ["Registered Massage Therapist"],
  },
  {
    id: "10",
    name: "Dr. Sophia Rodriguez",
    email: "s.rodriguez@example.com",
    specialty: "Neurological Physical Therapy",
    clinician_type: "Physical Therapist",
    tier: "Premier",
    phone: "555-0110",
    website: "https://sophiarodriguezpt.com",
    location: "Philadelphia, PA",
    clinic_address: "765 Brain Health Pl, Philadelphia, PA 19102",
    coordinates: { lat: 39.9526, lng: -75.1652 },
    bio: "Dr. Rodriguez specializes in treating patients with neurological conditions such as stroke, Parkinson's disease, and multiple sclerosis.",
    profile_image: "https://i.pravatar.cc/150?img=10",
    rating: 4.9,
    review_count: 65,
    accepting_new_patients: false,
    services: ["Stroke Rehab", "Balance Training", "Vestibular Therapy"],
    conditions_treated: [],
    languages_spoken: ["English", "Spanish"],
    certifications: ["Board-Certified Clinical Specialist in Neurologic Physical Therapy (NCS)"],
  },
  {
    id: "11",
    name: "Dr. Michael Brown",
    email: "m.brown@example.com",
    specialty: "Corrective Chiropractic",
    clinician_type: "Chiropractor",
    tier: "Preferred",
    location: "Austin, TX",
    clinic_address: "876 Posture Lane, Austin, TX 78701",
    coordinates: { lat: 30.2672, lng: -97.7431 },
    profile_image: "https://i.pravatar.cc/150?img=11",
    rating: 4.8,
    review_count: 140,
    accepting_new_patients: true,
    services: ["Postural Correction", "Spinal Adjustment"],
    conditions_treated: ["Low Back Pain", "Sciatica"],
    languages_spoken: ["English"],
  },
  {
    id: "12",
    name: "Chloe Kim, PT",
    email: "c.kim@example.com",
    specialty: "Women's Health PT",
    clinician_type: "Physical Therapist",
    tier: "Premier",
    location: "San Diego, CA",
    clinic_address: "987 Harmony Way, San Diego, CA 92101",
    coordinates: { lat: 32.7157, lng: -117.1611 },
    profile_image: "https://i.pravatar.cc/150?img=12",
    rating: 5.0,
    review_count: 92,
    accepting_new_patients: true,
    services: ["Pelvic Floor Therapy", "Prenatal/Postpartum Care"],
    conditions_treated: [],
    languages_spoken: ["English"],
  },
  {
    id: "13",
    name: "Ethan Williams, LMT",
    email: "e.williams@example.com",
    specialty: "Deep Tissue Massage",
    clinician_type: "Massage Therapist",
    tier: "Free",
    location: "Phoenix, AZ",
    clinic_address: "120 Desert Bloom Rd, Phoenix, AZ 85003",
    coordinates: { lat: 33.4484, lng: -112.0740 },
    profile_image: "https://i.pravatar.cc/150?img=13",
    rating: 4.6,
    review_count: 180,
    accepting_new_patients: true,
    services: ["Deep Tissue Massage", "Trigger Point Therapy"],
    conditions_treated: ["Neck Pain", "Low Back Pain"],
    languages_spoken: ["English"],
  },
  {
    id: "14",
    name: "Dr. Isabella Garcia",
    email: "i.garcia@example.com",
    specialty: "Acupuncture",
    clinician_type: "Acupuncturist",
    tier: "Preferred",
    location: "Dallas, TX",
    clinic_address: "231 Energy Flow Path, Dallas, TX 75201",
    coordinates: { lat: 32.7767, lng: -96.7970 },
    profile_image: "https://i.pravatar.cc/150?img=14",
    rating: 4.9,
    review_count: 110,
    accepting_new_patients: false,
    services: ["Acupuncture", "Cupping"],
    conditions_treated: ["Headaches & Migraines", "Carpal Tunnel Syndrome"],
    languages_spoken: ["English", "Spanish"],
  },
  {
    id: "15",
    name: "Dr. Noah Martinez",
    email: "n.martinez@example.com",
    specialty: "Chiropractic",
    clinician_type: "Chiropractor",
    tier: "Free",
    location: "Las Vegas, NV",
    clinic_address: "342 Spine Align St, Las Vegas, NV 89101",
    coordinates: { lat: 36.1699, lng: -115.1398 },
    profile_image: "https://i.pravatar.cc/150?img=15",
    rating: 4.5,
    review_count: 78,
    accepting_new_patients: true,
    services: ["Spinal Adjustment"],
    conditions_treated: ["Low Back Pain"],
    languages_spoken: ["English"],
  },
  {
    id: "16",
    name: "Liam O'Connell, PT",
    email: "l.oconnell@example.com",
    specialty: "Orthopedic Physical Therapy",
    clinician_type: "Physical Therapist",
    tier: "Premier",
    location: "Washington, D.C.",
    clinic_address: "453 Capitol View, Washington, D.C. 20001",
    coordinates: { lat: 38.9072, lng: -77.0369 },
    profile_image: "https://i.pravatar.cc/150?img=16",
    rating: 4.8,
    review_count: 134,
    accepting_new_patients: true,
    services: ["Manual Therapy", "Post-Surgical Rehab"],
    conditions_treated: ["Sports Injuries", "Tennis Elbow"],
    languages_spoken: ["English"],
  },
  {
    id: "17",
    name: "Ava Chen, LMT",
    email: "a.chen@example.com",
    specialty: "Swedish Massage",
    clinician_type: "Massage Therapist",
    tier: "Preferred",
    location: "Portland, OR",
    clinic_address: "564 Rose Garden Way, Portland, OR 97201",
    coordinates: { lat: 45.5152, lng: -122.6784 },
    profile_image: "https://i.pravatar.cc/150?img=17",
    rating: 4.9,
    review_count: 220,
    accepting_new_patients: true,
    services: ["Swedish Massage", "Aromatherapy"],
    conditions_treated: ["Headaches & Migraines"],
    languages_spoken: ["English", "Mandarin"],
  },
  {
    id: "18",
    name: "Dr. James Wilson",
    email: "j.wilson@example.com",
    specialty: "Acupuncture",
    clinician_type: "Acupuncturist",
    tier: "Free",
    location: "Atlanta, GA",
    clinic_address: "675 Peachtree St, Atlanta, GA 30308",
    coordinates: { lat: 33.7490, lng: -84.3880 },
    profile_image: "https://i.pravatar.cc/150?img=18",
    rating: 4.7,
    review_count: 85,
    accepting_new_patients: false,
    services: ["Acupuncture"],
    conditions_treated: ["Sciatica"],
    languages_spoken: ["English"],
  },
  {
    id: "19",
    name: "Dr. Emily Davis",
    email: "e.davis@example.com",
    specialty: "Pediatric Chiropractic",
    clinician_type: "Chiropractor",
    tier: "Premier",
    location: "Minneapolis, MN",
    clinic_address: "786 Lakefront Ave, Minneapolis, MN 55401",
    coordinates: { lat: 44.9778, lng: -93.2650 },
    profile_image: "https://i.pravatar.cc/150?img=19",
    rating: 5.0,
    review_count: 105,
    accepting_new_patients: true,
    services: ["Pediatric Adjustments", "Wellness Care"],
    conditions_treated: [],
    languages_spoken: ["English", "German"],
  },
  {
    id: "20",
    name: "Mason Taylor, PT",
    email: "m.taylor@example.com",
    specialty: "Geriatric Physical Therapy",
    clinician_type: "Physical Therapist",
    tier: "Preferred",
    location: "Tampa, FL",
    clinic_address: "897 Sunshine Blvd, Tampa, FL 33602",
    coordinates: { lat: 27.9506, lng: -82.4572 },
    profile_image: "https://i.pravatar.cc/150?img=20",
    rating: 4.8,
    review_count: 115,
    accepting_new_patients: true,
    services: ["Fall Prevention", "Mobility Training"],
    conditions_treated: ["Low Back Pain"],
    languages_spoken: ["English"],
  },
];