import { serve } from "https://deno.land/std@0.190.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req: Request) => {
  // This is required for CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const { prompt } = await req.json()

    // In a real-world scenario, you would call a service like OpenAI's GPT here with the prompt.
    const mockContent = `Based on your prompt: "${prompt}", here is some generated content.\n\nThis is a sample bio generated by the AI Content Assistant. It's designed to be SEO-friendly and engaging for potential patients. You can edit this content to better fit your personal style and practice details. Remember to include keywords like your specialty, location, and common conditions you treat.`

    return new Response(
      JSON.stringify({ content: mockContent }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  } catch (error: any) {
    return new Response(
        JSON.stringify({ error: error.message }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})