import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { CheckSquare, UserCheck, MailWarning } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";

const tasks = [
    {
        icon: <UserCheck className="h-5 w-5 text-blue-500" />,
        title: "Verify Dr. Evelyn Reed's Profile",
        description: "New Premier provider submission.",
        assignee: "https://github.com/shadcn.png",
        priority: "High"
    },
    {
        icon: <CheckSquare className="h-5 w-5 text-green-500" />,
        title: "Approve Marketing Content",
        description: "Generated by AI for 'Back Pain' campaign.",
        assignee: "https://github.com/shadcn.png",
        priority: "Medium"
    },
    {
        icon: <MailWarning className="h-5 w-5 text-yellow-500" />,
        title: "Review Support Ticket #1138",
        description: "Billing question from a Preferred provider.",
        assignee: "https://github.com/shadcn.png",
        priority: "Low"
    }
]

const TaskQueue = () => {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <CheckSquare className="h-5 w-5" />
          <span>Task Queue</span>
        </CardTitle>
        <CardDescription>Actionable items requiring admin attention.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {tasks.map((task, index) => (
            <div key={index} className="flex items-center gap-4">
                <div>{task.icon}</div>
                <div className="flex-1">
                    <p className="font-medium">{task.title}</p>
                    <p className="text-sm text-muted-foreground">{task.description}</p>
                </div>
                <Badge variant={task.priority === 'High' ? 'destructive' : 'secondary'}>{task.priority}</Badge>
                <Avatar className="h-8 w-8">
                    <AvatarImage src={task.assignee} alt="Assignee" />
                    <AvatarFallback>AD</AvatarFallback>
                </Avatar>
            </div>
        ))}
      </CardContent>
    </Card>
  );
};

export default TaskQueue;